### ISSUE TITLE
The version of the tflite_runtime

### ISSUE THREAD

**Issue by JoaquinSun** [SaneBow/PiDTLN#3]
What's your using version of the tflite_runtime for this project. I got some errors on invoking the model of node number 1 in the TensorFlow lite version 2.3. Thanks a lot.

**Comment by SaneBow** [comment]
I haven't run this project myself for a while. If I remember correctly, it may be TF Lite 2.4.x. Not sure if the problem you encountered is related to TF Lite version.

**Comment by SaneBow** [comment]
Have you solved this issue? 
If not, you may post your error log here and I can take a look later.

**Comment by JoaquinSun** [comment]
Thanks for your reply. By changing the TF lite version to 2.4.1 the problem was solved.
