### ISSUE TITLE
Can multi-core processing be used to improve performance？

### ISSUE THREAD

**Issue by FragrantRookie** [SaneBow/PiDTLN#4]
Is the current performance in the case of single core？Can multi-core processing be used to improve performance？

**Comment by SaneBow** [comment]
[aec_mp.py](https://github.com/SaneBow/PiDTLN/blob/main/aec_mp.py) is using multi-core. The last two columns of the [performance table](https://github.com/SaneBow/PiDTLN#performance) show the performance improvement of using multi-core for AEC.

**Comment by FragrantRookie** [comment]
Thank you for your reply！
